$schema: https://spec.openapis.org/oas/3.0/schema/2021-09-28
openapi: 3.0.3
info:
  title: Waku V2 node REST API 
  version: 1.0.0
  contact:
    name: VAC Team
    url: https://forum.vac.dev/

tags:
  - name: store
    description: Store REST API for WakuV2 node

paths:
  /store/v1/messages:
    get:
      summary: Retrieves historical messages on specific content topics.
      description: Returns history for a list of content topics with optional paging.
      operationId: getStoreMessages
      tags:
        - store
      responses:
        '200':
          description: The response to a query for historical messages.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoreMessagesResponse'
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '5XX':
          description: Unexpected error.
    

components:
  schemas:
    PubSubTopic:
      description: The pubsub topic on which a WakuMessage is published
      type: string

    ContentTopic:
      description: Message content topic for optional content-based filtering
      type: string


    StoreWakuMessage:
      type: object
      properties:
        payload:
          description: The message payload as a hex encoded data string
          type: string
        contentTopic:
          $ref: '#/components/schemas/ContentTopic'
        version:
          description: > 
            Message version. Used to indicate type of payload encryption. 
            Default version is 0 (no payload encryption).
          type: number
        timestamp:
          description: > 
            The time at which the message is generated by its sender. 
            This field holds the Unix epoch time in nanoseconds as a 64-bits integer value.
          type: number
      required:
        - payload

    StoreContentFilter:
      type: object
      properties:
        contentTopic:
          $ref: '#/components/schemas/ContentTopic'
      required:
        - "contentTopic"
        
    StoreIndex:
      description: >
        Message Index from which to perform pagination. If not included and forward is 
        set to true, paging will be performed from the beginning of the list. If not 
        included and forward is set to false, paging will be performed from the end of 
        the list.
      type: object
      properties:
        digest:
          description: A hash for the message at this index
          type: string
        receivedTime:
          description: UNIX timestamp in nanoseconds at which the message at this Index was received
          type: number
      required:
        - "digest"
        - "receivedTime"
      
    StorePagingOptions:
      description: Pagination information
      type: object
      properties:
        pageSize:
          description: Number of messages to retrieve per page
          type: number
        cursor:
          $ref: '#/components/schemas/StoreIndex'
        forward:
          description: true if paging forward, false if paging backward
          type: boolean
      required:
        - "pageSize"
        - "forward"


    StoreMessagesRequest:
      type: object
      properties:
        pubsubTopic:
          $ref: '#/components/schemas/PubSubTopic'
        contentFilters:
          description: Array of content filters to query for historical messages
          type: array
          items:
            $ref: '#/components/schemas/StoreContentFilter'
        startTime:
          description: > 
            The inclusive lower bound on the timestamp of queried WakuMessages. 
            This field holds the Unix epoch time in nanoseconds as a 64-bits integer value. 
          type: number
        endTime:
          description: >
            The inclusive upper bound on the timestamp of queried WakuMessages. 
            This field holds the Unix epoch time in nanoseconds as a 64-bits integer value.
          type: number
        pagingOptions:
          $ref: '#/components/schemas/StorePagingOptions'

    StoreMessagesResponse:
      type: object
      properties:
        messages:
          description: Array of retrieved historical messages
          type: array
          items:
            $ref: '#/components/schemas/StoreWakuMessage'
        pagingOptions:
          $ref: '#/components/schemas/StorePagingOptions' 
      required:
        - "messages"
      


